[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.18", features = ["headers"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.104"

[[bin]]
name = "app"
path = "src/main.rs"

